version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile  # Assuming the Dockerfile is in the same directory as docker-compose.yml
    image: avengers:latest  # Name the image to align with the Dockerfile build name
    ports:
      - "8080:8080"
    env_file:
      - .env