CREATE SCHEMA IF NOT EXISTS core;

create table users (
    id bigint generated by default as identity,
    email varchar(255) not null unique,
    name varchar(255) not null,
    telephone varchar(255) not null unique,
    type varchar(255) not null check (type in ('CIDADAO','ENFERMEIRO','BOMBEIRO','BRIGADISTA','FISCAL_AMBIENTAL','POLICIA_AMBIENTAL','DEFESA_CIVIL','FISCAL_SANITARIO')),
    primary key (id)
);

create table device (
    id bigint generated by default as identity,
    token varchar(255) not null,
    user_id bigint not null,
    last_latitude float(53) not null,
    last_longitude float(53) not null,
    number varchar(255),
    primary key (id)
);

create table incidence (
    id bigint generated by default as identity,
    date date not null,
    latitude float(53) not null,
    longitude float(53) not null,
    category varchar(255) not null check (category in ('INCENDIO','ENCHENTE','ALAGAMENTO','RISCO_ELETRICO','AFOGAMENTO','DESLIZAMENTO','OUTROS','POLUICAO_AMBIENTAL','TRAFICO_ANIMAIS','DESMATAMENTO_ILEGAL','CONTAMINACAO')),
    description varchar(1000) not null,
    user_id bigint not null,
    urgent boolean,
    status boolean not null,
    valid boolean,
    primary key (id)
);


alter table if exists device 
    add constraint FKk92m2qj36vn62ctp5pgbt4982 
    foreign key (user_id) 
    references users;

alter table if exists incidence 
    add constraint FK9hxiv1mdc3fb4jv4b0om02i2m 
    foreign key (user_id) 
    references users;
